version: '2'
services:
  service-nginx:
    image:  10.1.241.80:5000/peter/centos:dev
    environment:
      EDGE_A: '${EDGE_A}'
      EDGE_B: '${EDGE_B}'
      REDIS_IP: '${REDIS_IP}'
      REDIS_PORT: '${REDIS_PORT}'
    external_links:
    - mircservice-freamwork/edge-server:edge-server
  service-config:
    image: 10.1.241.80:5000/service-config:0.0.1-SNAPSHOT
    hostname: config
    environment:
      eureka.client.service-url.defaultZone: http://10.42.1.33:8761/eureka/
      spring.cloud.config.server.svn.uri: https://114.113.112.88:18093/svn/DAAS/trunk/Development/config
    stdin_open: true
    tty: true
    ports:
    - 8889:8889/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: group=microservice
  zipkin:
    image: 10.1.241.80:5000/zipkin
    stdin_open: true
    tty: true
    ports:
    - 9411:9411/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: group=microservice
      io.rancher.container.pull_image: always
      io.rancher.container.requested_ip: 10.42.246.135
  edge-server:
    image: 10.1.241.80:5000/service-edge:0.0.1-SNAPSHOT
    environment:
      spring.datasource.url: jdbc:mysql://10.1.241.81:3306/oauth2
      spring.datasource.username: root
      spring.datasource.password: 4rfv%TGB
      eureka.client.service-url.defaultZone: http://10.42.1.33:8761/eureka/
      spring.datasource.initialSize: '5'
      spring.datasource.minIdle: '5'
      spring.datasource.maxActive: '20'
      spring.datasource.maxWait: '60000'
      spring.datasource.timeBetweenEvictionRunsMillis: '60000'
      spring.datasource.minEvictableIdleTimeMillis: '300000'
      spring.datasource.validationQuery: SELECT 1
      spring.datasource.testWhileIdle: 'true'
      spring.datasource.testOnBorrow: 'true'
      spring.datasource.testOnReturn: 'true'
    stdin_open: true
    tty: true
    ports:
    - 8443:8443/tcp
    labels:
      io.rancher.container.pull_image: always
  service-monitor:
    image: 10.1.241.80:5000/service-monitor
    environment:
      eureka.client.service-url.defaultZone: http://10.42.1.33:8761/eureka/
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: group=microservice
  discovery2:
    image: 10.1.241.80:5000/service-discovery
    environment:
      eureka.client.service-url.defaultZone: http://10.42.1.33:8761/eureka/
      spring.profiles.active: peer2
      eureka.instance.preferIpAddress: 'true'
      eureka.instance.instance-id: $${spring.cloud.client.ipAddress}:$${server.port}
    stdin_open: true
    tty: true
    ports:
    - 8761:8761/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: group=microservice
      io.rancher.container.pull_image: always
      io.rancher.container.requested_ip: 10.42.1.44
  discovery1:
    image: 10.1.241.80:5000/service-discovery
    environment:
      eureka.client.service-url.defaultZone: http://10.42.1.44:8761/eureka/
      spring.profiles.active: peer1
      eureka.instance.preferIpAddress: 'true'
      eureka.instance.instance-id: $${spring.cloud.client.ipAddress}:$${server.port}
    stdin_open: true
    tty: true
    ports:
    - 8761:8761/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: group=microservice
      io.rancher.container.pull_image: always
      io.rancher.container.requested_ip: 10.42.1.33
  daas-monitor:
    image: 10.1.241.80:5000/daas-monitor
    environment:
      eureka.client.service-url.defaultZone: http://10.42.1.33:8761/eureka/
    stdin_open: true
    tty: true
    ports:
    - 9080:9080/tcp
    labels:
      io.rancher.container.pull_image: always
  company-info-service1:
    image: 10.1.241.80:5000/docker_company_info_service:1.6
    hostname: 10.42.86.228
    environment:
      zipkin.server-url: http://10.42.246.135:9411
      eureka.instance.preferIpAddress: 'true'
      eureka.instance.instance-id: $${spring.cloud.client.ipAddress}:$${server.port}
    stdin_open: true
    tty: true
    ports:
    - 9999:9090/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: group=microservice
      io.rancher.container.pull_image: always
      io.rancher.container.requested_ip: 10.42.86.228
