#  nginx image
microservice:
  image:  10.1.241.80:5000/peter/centos:dev
  environment:
    EDGE_A: '${EDGE_A}'
    EDGE_B: '${EDGE_B}'
    REDIS_IP: '${REDIS_IP}'
    REDIS_PORT: '${REDIS_PORT}'
  external_links:
    - mircservice-freamwork/edge-server:edge-server
  labels:
      io.rancher.scheduler.affinity:host_label: grx=mse