version: '2'
services:
  paper:
    image: 10.1.241.80:5000/tomcat:7.0.73-jre7
    stdin_open: true
    tty: true
    ports:
    - 8088:8080/tcp
    labels:
      io.rancher.container.pull_image: always
  wp-lb:
    image: rancher/lb-service-haproxy:v0.5.9
    ports:
    - 8088:8088/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
